// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsuiqplxllaqoamhnrvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzdWlxcGx4bGxhcW9hbWhucnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NDUwNzksImV4cCI6MjA1MTIyMTA3OX0.MP2sLeYIAqOQdNgxqUugPEbNlKf4_XpNjJAVB63t9Jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);